version: '3.9'
services:
    gateway:
        build:
            args:
                user: idanieldrew
                uid: 1000
            context: docker/
            dockerfile: Dockerfile
        image: gateway
        container_name: gateway_application
        restart: unless-stopped
        depends_on:
            - gateway_database
            - gateway_webserver
        working_dir: /var/www
        volumes:
            - .:/var/www
        #            - ./docker/php.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - gateway_network

    gateway_webserver:
        image: nginx:1.21.3
        container_name: gateway_server
        restart: always
        tty: true
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./docker/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - gateway_network

    gateway_database:
        image: postgres:14.2-alpine
        container_name: gateway_db
        restart: unless-stopped
        tty: true
        ports:
            - "54320:5432"
        environment:
            POSTGRES_DB: "gateway"
            POSTGRES_USER: "dani"
            POSTGRES_PASSWORD: "password"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        volumes:
            - gateway_db:/var/lib/postgresql/data
        networks:
            - gateway_network


networks:
    gateway_network:
        driver: bridge

volumes:
    gateway_db:
        driver: local
